name: Test cleanup

on:
  pull_request:
    branches-ignore: master
  push:
    branches-ignore: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      registry: itmindbox
      image: dev_ui_kit

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1

      - name: Transform branch name
        run: echo "##[set-output name=branch;]$(echo $EXT_BRANCH_NAME | sed 's/refs\/heads\///g' | sed 's/[_.\/]/-/g')"
        id: transform_branch
        env:
          EXT_BRANCH_NAME: ${{ github.ref }}

      - name: Get branch name hash
        run: echo "##[set-output name=hash_payload;]$(echo $BRANCH | md5sum | sed 's/  -//g')"
        id: branch_hash
        env:
          BRANCH: ${{ steps.transform_branch.outputs.branch }}

      - name: Remove docker image
        run: ./scripts/cleaner.sh ${{ secrets.DOCKER_HUB_LOGIN_PAYLOAD }} ${{ steps.transform_branch.outputs.branch }}